require 'yaml'

string = "  <key>Gen</key>
  <string>GEN</string>
  <key>Exod</key>
  <string>EXO</string>
  <key>Lev</key>
  <string>LEV</string>
  <key>Num</key>
  <string>NUM</string>
  <key>Deut</key>
  <string>DEU</string>
  <key>Josh</key>
  <string>JOS</string>
  <key>Judg</key>
  <string>JDG</string>
  <key>Ruth</key>
  <string>RUT</string>
  <key>1Sam</key>
  <string>1SA</string>
  <key>2Sam</key>
  <string>2SA</string>
  <key>1Kgs</key>
  <string>1KI</string>
  <key>2Kgs</key>
  <string>2KI</string>
  <key>1Chr</key>
  <string>1CH</string>
  <key>2Chr</key>
  <string>2CH</string>
  <key>Ezra</key>
  <string>EZR</string>
  <key>Neh</key>
  <string>NEH</string>
  <key>Esth</key>
  <string>EST</string>
  <key>Job</key>
  <string>JOB</string>
  <key>Ps</key>
  <string>PSA</string>
  <key>Prov</key>
  <string>PRO</string>
  <key>Eccl</key>
  <string>ECC</string>
  <key>Song</key>
  <string>SNG</string>
  <key>Isa</key>
  <string>ISA</string>
  <key>Jer</key>
  <string>JER</string>
  <key>Lam</key>
  <string>LAM</string>
  <key>Ezek</key>
  <string>EZK</string>
  <key>Dan</key>
  <string>DAN</string>
  <key>Hos</key>
  <string>HOS</string>
  <key>Joel</key>
  <string>JOL</string>
  <key>Amos</key>
  <string>AMO</string>
  <key>Obad</key>
  <string>OBA</string>
  <key>Jonah</key>
  <string>JON</string>
  <key>Mic</key>
  <string>MIC</string>
  <key>Nah</key>
  <string>NAM</string>
  <key>Hab</key>
  <string>HAB</string>
  <key>Zeph</key>
  <string>ZEP</string>
  <key>Hag</key>
  <string>HAG</string>
  <key>Zech</key>
  <string>ZEC</string>
  <key>Mal</key>
  <string>MAL</string>
  <key>Matt</key>
  <string>MAT</string>
  <key>Mark</key>
  <string>MRK</string>
  <key>Luke</key>
  <string>LUK</string>
  <key>John</key>
  <string>JHN</string>
  <key>Acts</key>
  <string>ACT</string>
  <key>Rom</key>
  <string>ROM</string>
  <key>1Cor</key>
  <string>1CO</string>
  <key>2Cor</key>
  <string>2CO</string>
  <key>Gal</key>
  <string>GAL</string>
  <key>Eph</key>
  <string>EPH</string>
  <key>Phil</key>
  <string>PHP</string>
  <key>Col</key>
  <string>COL</string>
  <key>1Thess</key>
  <string>1TH</string>
  <key>2Thess</key>
  <string>2TH</string>
  <key>1Tim</key>
  <string>1TI</string>
  <key>2Tim</key>
  <string>2TI</string>
  <key>Titus</key>
  <string>TIT</string>
  <key>Phlm</key>
  <string>PHM</string>
  <key>Heb</key>
  <string>HEB</string>
  <key>Jas</key>
  <string>JAS</string>
  <key>1Pet</key>
  <string>1PE</string>
  <key>2Pet</key>
  <string>2PE</string>
  <key>1John</key>
  <string>1JN</string>
  <key>2John</key>
  <string>2JN</string>
  <key>3John</key>
  <string>3JN</string>
  <key>Jude</key>
  <string>JUD</string>
  <key>Rev</key>
  <string>REV</string>
  <key>Tob</key>
  <string>TOB</string>
  <key>Jdt</key>
  <string>JDT</string>
  <key>AddEsth</key>
  <string>ESG</string>
  <key>Wis</key>
  <string>WIS</string>
  <key>Sir</key>
  <string>SIR</string>
  <key>Bar</key>
  <string>BAR</string>
  <key>EpJer</key>
  <string>LJE</string>
  <key>PrAzar</key>
  <string>S3Y</string>
  <key>Sus</key>
  <string>SUS</string>
  <key>Bel</key>
  <string>BEL</string>
  <key>1Macc</key>
  <string>1MA</string>
  <key>2Macc</key>
  <string>2MA</string>
  <key>3Macc</key>
  <string>3MA</string>
  <key>4Macc</key>
  <string>4MA</string>
  <key>1Esd</key>
  <string>1ES</string>
  <key>2Esd</key>
  <string>2ES</string>
  <key>PrMan</key>
  <string>MAN</string>
  <key>Ps151</key>
  <string>PS2</string>
  <key>Odes</key>
  <string>ODA</string>
  <key>PssSol</key>
  <string>PSS</string>
  <key>4Esd</key>
  <string>EZA</string>
  <key>2Bar</key>
  <string>2BA</string>
  <key>EpBar</key>
  <string>LBA</string>
  <key>Jub</key>
  <string>JUB</string>
  <key>1En</key>
  <string>ENO</string>
  <key>4Bar</key>
  <string>4BA</string>
  <key>EpLao</key>
  <string>LAO</string>
  <key>Lkac</key>
  <string>LKA</string>
"
matches = string.scan(/<key>(.+)<\/key>\W+<string>(.+)<\/string>/)

matches.each {|m| puts "'#{m[0].downcase}': '#{m[1]}'" }

#puts YAML::load_file(File.expand_path('../config/osis_to_usfm.yml', __FILE__)).class