FROM in.thewardro.be:4567/docker/nodejs:8.11.3

RUN mkdir -p /app && chown node:node /app
WORKDIR /app

COPY elaphros/package.json elaphros/package-lock.json /app/
RUN npm install ci --production

COPY elaphros/ /app

EXPOSE 80

CMD ["/sbin/my_init", "--", "node", "./server.js"]
